config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'searches/search'
  root 'invoices#index'
  resources :invoices, only: %w(new create index show)
  resources :requestors, only: %w(new create index)
  resources :sessions, only: %w(new create destroy)
  resources :users, only: %w(new create index edit update destroy)
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  has_many :invoice_details, dependent: :destroy
  has_many :pictures, dependent: :destroy
  belongs_to :user
  accepts_nested_attributes_for :invoice_details, allow_destroy: true, reject_if: lambda {|attributes| attributes['subject'].blank? and attributes['quantity'].blank? and attributes['unit_price'].blank?}
  accepts_nested_attributes_for :pictures, allow_destroy: true, reject_if: lambda {|attributes| attributes['image'].blank?}
  belongs_to :requestor
  validates :subject, presence: true
  validates :issued_on, presence: true
  validates :due_on, presence: true
  validates :api_status, presence: true
  enum api_status: { 未連携: 0, 完了: 1 }
  scope :search_by_due_on_year, -> (from, to){ where(due_on: from..to)}
  scope :search_by_due_on_month, -> (from, to){ where(due_on: from..to)}
  scope :search_by_due_on_date, -> (due_on){ where(due_on: "#{due_on}")}
  scope :search_by_subject, -> (subject){ where("subject LIKE ?", "%#{subject}%")}
  # validates :issued_on_before_type_cast, format: { with: /\A(2014)-([01]\d)-([0-3]\d)\z/ }, unless: ->(rec){ rec.due_on_before_type_cast.blank? }
  # validates :due_on_before_type_cast, format: { with: /\A(2014)-([01]\d)-([0-3]\d)\z/ }, unless: ->(rec){ rec.due_on_before_type_cast.blank? }
  # validate :start_end_check

  def start_end_check
    errors.add(:due_on, "は開始日より前の日付は登録できません。") unless self.issued_on <= self.due_on 
  end

  def subtotal_price_without_tax
    subtotal = 0
    self.invoice_details.each do |invoice_detail|
      invoice_detail.subject
      quantity = invoice_detail.quantity
      price = invoice_detail.unit_price
      sum = quantity * price
      subtotal += sum
    end
    subtotal
  end

  def total_price_with_tax
    total = 0
    self.invoice_details.each do |invoice_detail|
      invoice_detail.subject
      quantity = invoice_detail.quantity
      price = invoice_detail.unit_price
      subtotal = quantity * price
      sum = (quantity * price *1.10).to_i
      total += sum
    end
    total = total.to_i
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :auth_google_drive
  before_action :get_freee_authentication_code, only: %i[new]
  
  def index
    auth_google_drive
    @invoices = Invoice.all.includes(:requestor)
  end

  def new
    # アクセストークンが初回かの判定
    if session[:access_token] && session[:refresh_token] # 2回目以降であれば、リフレッシュトークンを用いてアクセストークンを更新する
      token_url  = "https://accounts.secure.freee.co.jp/public_api/token"
      connection = Faraday::Connection.new(url: token_url) do|conn|
        conn.request :url_encoded
        conn.adapter Faraday.default_adapter
      end
      response = connection.post do |request|
        request.options.timeout = 300
        request.body = {
          grant_type: "refresh_token",
          client_id: ENV['FREEE_CLIENT_ID'],
          client_secret: ENV['FREEE_CLIENT_SECRET'],
          refresh_token: session[:refresh_token],
          redirect_uri: "http://localhost:3000/invoices/new"
        }
      end
      session[:access_token] = JSON.parse(response.body)["access_token"]
      session[:refresh_token] = JSON.parse(response.body)["refresh_token"]
    else # 初回であれば、認可コードを用いてアクセストークンを取得する
      token_url  = "https://accounts.secure.freee.co.jp/public_api/token"
      connection = Faraday::Connection.new(url: token_url) do|conn|
        conn.request :url_encoded
        conn.adapter Faraday.default_adapter
      end
      response = connection.post do |request|
        request.options.timeout = 300
        request.body = {
          grant_type: "authorization_code",
          client_id: ENV["FREEE_CLIENT_ID"],
          client_secret: ENV["FREEE_CLIENT_SECRET"],
          code: session[:authentication_code],
          redirect_uri: "http://localhost:3000/invoices/new"
        }
      end
      session[:access_token] = JSON.parse(response.body)["access_token"]
      session[:refresh_token] = JSON.parse(response.body)["refresh_token"]
    end
    @invoice = Invoice.new
    5.times {@invoice.invoice_details.build}
    3.times {@invoice.pictures.build}
  end

  def create
    # freeeとの疎通確認
    tax_url  = "https://api.freee.co.jp/api/1/taxes/companies/10965275"
    connection = Faraday::Connection.new(url: tax_url) do|conn|
      conn.request :url_encoded
      conn.adapter Faraday.default_adapter
    end
    response = connection.get do |request|
      request.options.timeout = 300
      request.headers["Authorization"] = "Bearer #{session[:access_token]}"
      request.body = {
        grant_type: "refresh_token",
        client_id: ENV['FREEE_CLIENT_ID'],
        client_secret: ENV['FREEE_CLIENT_SECRET'],
        refresh_token: session[:refresh_token]
      }
    end
    unless response.status == 200
      respond_to do |format|
        format.turbo_stream { redirect_to new_invoice_path, notice: "freeeへの認証が切れたため再接続しました。最初から入力し直してください" ; return}
      end
    end
    @invoice = Invoice.new(invoice_params)
    @invoice.user_id = current_user.id
    if params[:invoice][:pictures_attributes]
      file1 = params[:invoice][:pictures_attributes][:"0"][:image]
      files = []
      files << file1
      if params[:invoice][:pictures_attributes][:"1"]
        file2 = params[:invoice][:pictures_attributes][:"1"][:image]
        files << file2
        if params[:invoice][:pictures_attributes][:"2"]
          file3 = params[:invoice][:pictures_attributes][:"2"][:image]
          files << file3
        end
      end
      # 請求書の保存が成功した場合
      if @invoice.save
        # Google Driveへの画像連携処理開始
        # 格納先のフォルダーの存在を確認し、なければ作成する
        top_folder = @drive.file_by_title("請求書")
        if top_folder.file_by_title(params[:invoice]["issued_on(1i)"]+"年")
          seconed_level_folder = top_folder.file_by_title(params[:invoice]["issued_on(1i)"]+"年")
          if seconed_level_folder.file_by_title(params[:invoice]["issued_on(2i)"]+"月")
            third_level_folder = seconed_level_folder.file_by_title(params[:invoice]["issued_on(2i)"]+"月")
          else
            third_level_folder = seconed_level_folder.create_subfolder(params[:invoice]["issued_on(2i)"]+"月")
          end
        else
          seconed_level_folder = top_folder.create_subfolder(params[:invoice]["issued_on(1i)"]+"年")
          third_level_folder = seconed_level_folder.create_subfolder(params[:invoice]["issued_on(2i)"]+"月")
        end
        # 画像ファイルのアップロード処理
        files.each.with_index do |file, index|
          filename = "#{params[:invoice]["issued_on(1i)"]}年#{params[:invoice]["issued_on(2i)"]}月_#{params[:invoice][:subject]}_#{index + 1}"
          file_ext = File.extname(filename)
          file_find = third_level_folder.upload_from_file(File.absolute_path(file), filename, convert: false)
        end
        # Google Driveへの画像連携処理終了
        # 成功したかのチェック
        file_upload_checks = []
        files.length.times do |i|
          filename = "#{params[:invoice]["issued_on(1i)"]}年#{params[:invoice]["issued_on(2i)"]}月_#{params[:invoice][:subject]}_#{i + 1}"
          file_ext = File.extname(filename)
          file_upload_checks << @drive.file_by_title(filename)
        end
        if file_upload_checks.include?(nil)
          file = nil
        else # 成功した場合picturesテーブルに保存されたレコードをすぐに呼び出して、google_drive_urlカラムを更新する
          pictures = Picture.where(invoice_id: Invoice.last.id)
          pictures.each.with_index do |picture, index|
            filename = "#{params[:invoice]["issued_on(1i)"]}年#{params[:invoice]["issued_on(2i)"]}月_#{params[:invoice][:subject]}_#{index + 1}"
            file_ext = File.extname(filename)
            file = @drive.file_by_title(filename)
            picture.update(google_drive_url: "https://drive.google.com/uc?export=view&id=#{file.id}")
          end
        end
        # freeeへの請求書内容連携処理開始
        deal_url  = "https://api.freee.co.jp/api/1/deals"
        connection = Faraday::Connection.new(url: deal_url) do|conn|
          conn.request :url_encoded
          conn.adapter Faraday.default_adapter
        end
        # リクエストボディに入れるdetailsをあらかじめ整形
        @invoice_details = InvoiceDetail.where(invoice_id: Invoice.last.id)
        details = []
        @invoice_details.each do |invoice_detail|
          description = invoice_detail.subject
          amount = (invoice_detail.unit_price * invoice_detail.quantity * 1.10).to_i
          details << {
            "tax_code": 136,
            "account_item_id": 767592023,
            "amount": amount,
            "description": description
          }
        end
        # POSTメソッドでfreeeに連携
        response = connection.post do |request|
          request.options.timeout = 300
          request.headers["Content-Type"] = "application/json"
          request.headers["Authorization"] = "Bearer #{session[:access_token]}"
          request.body = {
            "issue_date": @invoice.issued_on,
            "type": "expense",
            "company_id": 10965275,
            "due_date": @invoice.due_on,
            "details": details
          }.to_json
        end
        # freeeへの請求書内容連携処理終了
        # 成功したかのチェック
        if response.status == 201 # 成功した場合invoicesテーブルに保存されたレコードをすぐに呼び出して、api_statusカラムを更新する
          status = 201
          invoice = Invoice.last
          invoice.update(api_status: 1)
        else
          error = response.body.force_encoding("UTF-8")
        end
        # 最終判定
        if file == nil && status != 201
          respond_to do |format|
            format.turbo_stream { redirect_to invoices_path, notice: "請求書を登録しました。画像のアップロードに失敗しました。手動でGoogle Driveに登録してください。ファイル名は yyyy年mm月_件名_何枚目.拡張子 です。freeeへの連携に失敗しました。管理者に連絡してください。" }
          end
        elsif file == nil
          respond_to do |format|
            format.turbo_stream { redirect_to invoices_path, notice: "請求書を登録しました。画像のアップロードに失敗しました。手動でGoogle Driveに登録してください。ファイル名は yyyy年mm月_件名_何枚目.拡張子 です。" }
          end
        elsif status != 201
          respond_to do |format|
            format.turbo_stream { redirect_to invoices_path, notice: "請求書を登録しました。freeeへの連携に失敗しました。以下のエラーメッセージを管理者に伝えてください。#{response.body}" }
          end
        else
          respond_to do |format|
            format.turbo_stream { redirect_to invoices_path, notice: "請求書を登録しました" }
          end
        end
      # 請求書の保存が失敗した場合
      else
        flash.now[:danger] = "請求書の登録に失敗しました"
        render :new, status: :unprocessable_entity
      end
    # 画像が選択されていない場合
    else
      flash.now[:danger] = "画像選択してください"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @invoice = Invoice.find(params[:id])
    @pictures = Picture.where(invoice_id: params[:id])
    @subtotal = @invoice.subtotal_price_without_tax
    @total = @invoice.total_price_with_tax
  end

  private

  def invoice_params
    params.require(:invoice).permit(:requestor_id, :subject, :issued_on, :due_on, :api_status, :memo, invoice_details_attributes: [:subject, :quantity, :unit_price, :_destroy, :id], pictures_attributes: [:image, :_destroy, :id])
  end

  def auth_google_drive
    client = OAuth2::Client.new(
      ENV['GOOGLE_DRIVE_CLIENT_ID'], ENV['GOOGLE_DRIVE_CLIENT_SECRET'],
      site: 'https://accounts.google.com',
      token_url: '/o/oauth2/token',
      authorize_url: '/o/oauth2/auth'
    )

    @token = OAuth2::AccessToken.from_hash(
      client, { refresh_token: ENV['GOOGLE_DRIVE_REFRESH_TOKEN'], expires_at: 3600 }
    ).refresh!.token

    @drive = GoogleDrive.login_with_oauth(@token)
  end

  #認可コードの取得
  def get_freee_authentication_code
    if session[:authentication_code]
    else
      if request.query_string.match(/code=(.*)/)
        query_string = request.query_string.match(/code=(.*)/)
        session[:authentication_code] = query_string[1]
      else
        redirect_to 'https://accounts.secure.freee.co.jp/public_api/authorize?client_id=3dc6ffc89b240841f8fb2fc7b48dce4d8fc4d40c32f93bd7e8c23f75b3bc2c38&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Finvoices%2Fnew&response_type=code&prompt=select_company', allow_other_host: true
      end
    end
  end

end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/index.html.erb
<h1>請求書一覧</h1>
<%= form_with scope: :search, url: searches_search_path, method: :get, local: true do |form| %>
  <%= form.date_select :due_on, include_blank: "日付..." %>
  <%= form.search_field :subject, placeholder: "件名..." %>
  <%= form.select :requestor_id, Requestor.all.collect { |p| [ p.name, p.id ] }, include_blank: "請求元..." %>
  <%= form.submit "検索する" %>
<% end %>
<table>
  <tr>
    <th>支払い期日</th>
    <th>件名</th>
    <th>請求元</th>
    <th>freee連携</th>
  </tr>
  <% @invoices.each do |invoice| %>
    <tr>
      <td><%= l invoice.due_on, format: :default %></td>
      <td><%= link_to invoice.subject, invoice_path(invoice.id) %></td>
      <td><%= invoice.requestor.name %></td>
      <td><%= invoice.api_status %></td>
    </tr>
  <% end %>
</table>


<%# @files.each do |file| %>
  <%#= image_tag "https://drive.google.com/uc?id=#{file.id}" %>
<%# end %>

app/views/invoices/new.html.erb
<h1>請求書登録</h1>
<%= form_with(model: @invoice, local: true) do |form| %>
  <% if @invoice.errors.any? %>
    <div id="error_expanation">
      <%= @invoice.errors.count %>件のエラーがあります。
      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="pictures-container" id="pictures">
    <%= form.fields_for :pictures do |picture| %>
      <div class="picture" style="display: none">
        <div>
          <p><%= picture.label :image %></p>
          <p><%= picture.file_field :image, capture: "camera" %></p>
        </div>
      </div>
    <% end %>
  </div>
  <div>
    <button id="add-picture-form" type="button">追加</button>
    3枚まで保存可能
  </div>
  <%= turbo_frame_tag "first_turbo_frame" do %>
    <div>
      <p><%= form.label :請求元 %></p>
      <p><%= form.select :requestor_id, Requestor.all.collect { |p| [ p.name, p.id ] } %>
      <%= link_to "請求元の追加", new_requestor_path %></p>
    </div>
  <% end %>
  <div>
    <p><%= form.label :issued_on %></p>
    <p><%= form.date_select :issued_on %></p>
  </div>
  <div>
    <p><%= form.label :subject %></p>
    <p><%= form.text_field :subject %></p>
  </div>
  <div>
    <p><%= form.label :due_on %></p>
    <p><%= form.date_select :due_on %></p>
  </div>
  <div>
    <p><%= form.label :memo %></p>
    <p><%= form.text_area :memo %></p>
  </div>
  <div class="invoice-details-container" id="invoice-details">
    <%= form.fields_for :invoice_details do |invoice_detail| %>
      <div class="invoice-detail" style="display: none">
        <div>
          <p><%= invoice_detail.label :subject %></p>
          <p><%= invoice_detail.text_field :subject %></p>
        </div>
        <div>
          <p><%= invoice_detail.label :quantity %></p>
          <p><%= invoice_detail.number_field :quantity %></p>
        </div>
        <div>
          <p><%= invoice_detail.label :unit_price %></p>
          <p><%= invoice_detail.number_field :unit_price %></p>
        </div>
      </div>
    <% end %>
  </div>
  <div>
    <button id="add-invoice-detail-form" type="button">追加</button>
    5行まで追加可
  </div>
  <p><%= form.submit %></p>
<% end %>

app/views/invoices/show.html.erb
<h1>請求書詳細</h1>
<% @pictures.each do |picture| %>
  <%= image_tag picture.google_drive_url %>
<% end %>
<table>
  <tr>
    <th>請求元</th>
    <th>件名</th>
    <th>期日</th>
  </tr>
  <tr>
    <td><%= Requestor.find(@invoice.requestor_id).name %></td>
    <td><%= @invoice.subject %></td>
    <td><%= l @invoice.due_on, format: :default %></td>
  </tr>
  <tr>
    <th>小計</th>
    <th>合計</th>
    <th>メモ</th>
  </tr>
  <tr>
    <td><%= @subtotal.to_s(:delimited) %>円</td>
    <td><%= @total.to_s(:delimited) %>円</td>
    <td><%= @invoice.memo %></td>
  </tr>
  <tr>
    <th>内訳</th>
    <th>数量</th>
    <th>税抜き単価</th>
    <th>金額</th>
  </tr>
  <% @invoice.invoice_details.each do |invoice_detail| %>
  <tr>
    <td><%= invoice_detail.subject %></td>
    <td><%= invoice_detail.quantity %></td>
    <td><%= invoice_detail.unit_price.to_s(:delimited) %>円</td>
    <td><%= (invoice_detail.quantity * invoice_detail.unit_price).to_s(:delimited) %>円</td>
  </tr>
  <% end %>

  <tr>
    <th>freee連携</th>
    <th>登録者</th>
  </tr>
  <tr>
    <td><%= @invoice.api_status %></td>
    <td><%= @invoice.user.email %>さん</td>
  </tr>
</table>