config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'searches/search'
  root 'invoices#index'
  resources :invoices, only: %w(new create index show)
  resources :requestors, only: %w(new create index)
  resources :sessions, only: %w(new create destroy)
  resources :users, only: %w(new create index edit update destroy)
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @invoices = Invoice.all.includes(:requestor)
    if params[:search].present?
      if params[:search]["due_on(1i)"].present? && params[:search]["due_on(2i)"].present? && params[:search]["due_on(3i)"].present?
        year = params[:search]["due_on(1i)"]
        month = params[:search]["due_on(2i)"]
        date = params[:search]["due_on(3i)"]
        begin
          due_on = Date.parse(year + "-" + month + "-" + date)
        rescue
        end
        @invoices = @invoices.search_by_due_on_date(due_on)
      elsif params[:search]["due_on(1i)"].present? && params[:search]["due_on(2i)"].present?
        year = params[:search]["due_on(1i)"]
        month = params[:search]["due_on(2i)"]
        date = "1"
        due_on = Date.parse(year + "-" + month + "-" + date)
        from = due_on.beginning_of_month
        to = due_on.end_of_month
        @invoices = @invoices.search_by_due_on_month(from, to)
      elsif params[:search]["due_on(1i)"].present?
        year = params[:search]["due_on(1i)"]
        month = "1"
        date = "1"
        due_on = Date.parse(year + "-" + month + "-" + date)
        from = due_on.beginning_of_year
        to = due_on.end_of_year
        @invoices = @invoices.search_by_due_on_year(from, to)
      elsif params[:search]["due_on(2i)"].present? || params[:search]["due_on(3i)"].present?
        @invoices = []
      end
      if params[:search][:subject].present?
        @invoices = @invoices.search_by_subject(params[:search][:subject])
      end
      if params[:search][:requestor_id].present?
        requestor_id = params[:search][:requestor_id]
        @invoices = @invoices.where(requestor_id: requestor_id)
      end
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<h1>検索結果</h1>
<%= form_with scope: :search, url: searches_search_path, method: :get, local: true do |form| %>
  <%= form.date_select :due_on, include_blank: "日付..." %>
  <%= form.search_field :subject, placeholder: "件名..." %>
  <%= form.select :requestor_id, Requestor.all.collect { |p| [ p.name, p.id ] }, include_blank: "請求元..." %>
  <%= form.submit "検索する" %>
  <%= link_to "結果をクリア", invoices_path %>
<% end %>
<table>
  <tr>
    <th>支払い期日</th>
    <th>件名</th>
    <th>請求元</th>
    <th>freee連携</th>
  </tr>
  <% @invoices.each do |invoice| %>
    <tr>
      <td><%= l invoice.due_on, format: :default %></td>
      <td><%= link_to invoice.subject, invoice_path(invoice.id) %></td>
      <td><%= invoice.requestor.name %></td>
      <td><%= invoice.api_status %></td>
    </tr>
  <% end %>
</table>